version: '3'
services:

  mongodb:
    restart: always
    container_name: dockergs_mongodb
    image: shiroinekotfs/genshindocker:_mongodb
    deploy:
      resources:
        limits:
          memory: 1G
    ports:
      - '27017:27017'
    volumes:
      - './run/db:/data/db'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ADMIN}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}

  grasscutter:
    restart: always
    container_name: dockergs
    image: shiroinekotfs/genshindocker:ubuntu-gc-5.0
    deploy:
      resources:
        limits:
          memory: 2G
    command: >-
      --database 'mongodb://${MONGODB_ADMIN}:${MONGODB_PASSWORD}@mongodb:27017' --web_ip
      '0.0.0.0' --web_port "80" --game_ip '0.0.0.0' --java '-Xmx2G' --ssl
      "false" --web_url_ssl "false"
    volumes:
      - './res/Resources:/home/dockergs/resources'
    ports:
      - '80:80'
      - '443:443'
      - '22102:22102/udp'
    depends_on:
      - mongodb
    stdin_open: true
    tty: true
    init: true
